### PR TITLE
Fixing some strings-en errors

### PR DESCRIPTION
**Pull request by Vv2233Bb**
zo-shin. Btw. Thank you for telling me about the  \ . One more question: How to make the "-" visible?

### CODE REVIEW

**Comment by zo-shin** [comment]
Hyphen can be used directly.

**Comment by Vv2233Bb** [comment]
So the backslash is useless?

**Comment by zo-shin** [comment]
It's used without the back slash.

**Comment by Vv2233Bb** [comment]
But why is it invisible in the app?

**Comment by zo-shin** [comment]
Which string is invisible?

**Comment by Vv2233Bb** [comment]
The hyphen is invisible in the User-Agent string

**Comment by zo-shin** [comment]
I tested your string and found it work well, not like what you described.

**Comment by Vv2233Bb** [comment]
Strange... Opened Via on 2 different phones and the hyphen was invisible in both phones. Everything else is OK tho?

**Comment by zo-shin** [comment]
I didn't see any major problems, though I don't agree to the changes completely.

**Comment by Vv2233Bb** [comment]
OK... What's wrong?

**Comment by zo-shin** [comment]
I don't know if the strings in line 99, 100 and 101 can be shown completely, because there's an icon above them, which makes the space narrow.

**Comment by Vv2233Bb** [comment]
My idea there is that only the part before \n will be visible under the icon and the part after \n will only be visible in the pop-up.

**Comment by zo-shin** [comment]
I don't think it will work that way. What you did is just separating it into two lines.

**Comment by Vv2233Bb** [comment]
Yes. I seperated it because normally string would cut-off Like this: Blocking Im...
My goal is to make the text under the icon say if it is on, off or wifi only and the pop-up that pops up eplain what is turned on or off

**Comment by LakorTi** [comment]
Thanks for your work! But I think some words are confused. Sorry for closing this pr.

**Pull request closed without merging**
