### PR TITLE
Fixed Many String Errors

### PR DESCRIPTION
**Pull request by zo-shin**

### CODE REVIEW

**Comment by Vv2233Bb** [comment]
Are you just trying to revert the changes?

**Comment by zo-shin** [comment]
Not completely, but many changes of strings you made are incorrect. The back slash \ before the apostrophe ' is necessary, like don\ 't instead of your don't.

**Comment by Vv2233Bb** [comment]
What about User-Agent and other places where i made the strings smaller? The only fixes I see are  the \ and showing images.

**Comment by zo-shin** [comment]
Hyphenating here is not a problem, but it’s not very necessary. I prefer the original strings.

**Comment by zo-shin** [comment]
Back slash is used with certain strings together to achieve some special purposes, like \ n means ENTER (see line 24, 124, etc.), \ ’ means ONE apostrophe ONLY (see line 124, 129, 296, etc.). Without it, the app will think the apostrophe in don’t is for string quotation, causing all strings after the apostrophe invisible on the UI.

**Pull request closed without merging**
