### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by f1j4r**
update strings.xml for indonesian language.

### CODE REVIEW

**Comment by f1j4r** [comment]
[Via-07479126a38adca4a6458f546c4ba3cba850f525.zip](https://github.com/LakorTi/Via/files/1167459/Via-07479126a38adca4a6458f546c4ba3cba850f525.zip)

**Comment by somporlove100** [comment]
ทำตาม

**Comment by LakorTi** [comment]
Hey kind man. Next time you should modify the indonesian language string in value-in folder. Anyway, thanks very much.

**Comment by f1j4r** [comment]
you're welcome..
sorry about it, coz i'm still newbie..
Pada tanggal 7 Agt 2017 14:48, "Lakor" <notifications@github.com> menulis:

**Pull request merged**
